twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
      recaptcha_client_key: '%env(RECAPTCHA_CLIENT_KEY)%'
      google_map_key: '%env(GOOGLE_MAPS_KEY)%'